// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZigjzjoSEx6j8WVjjxq5f3fwvDEFP8Z4',
    appId: '1:390088026181:web:926dbcfb0ad3353786db2c',
    messagingSenderId: '390088026181',
    projectId: 'care-31db0',
    authDomain: 'care-31db0.firebaseapp.com',
    storageBucket: 'care-31db0.appspot.com',
    measurementId: 'G-RQR93JVKM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXeOaEsgg1VQLlNeF7oBVmtUM9PXUJ9iU',
    appId: '1:390088026181:android:0710d0172fd2703586db2c',
    messagingSenderId: '390088026181',
    projectId: 'care-31db0',
    storageBucket: 'care-31db0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD562-NjAKU4DSw9JJUh4a2sIg_gmkAIkk',
    appId: '1:390088026181:ios:e8f5dabb20650e0886db2c',
    messagingSenderId: '390088026181',
    projectId: 'care-31db0',
    storageBucket: 'care-31db0.appspot.com',
    iosBundleId: 'com.health.careapp.careApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD562-NjAKU4DSw9JJUh4a2sIg_gmkAIkk',
    appId: '1:390088026181:ios:e77e42d2598d30e086db2c',
    messagingSenderId: '390088026181',
    projectId: 'care-31db0',
    storageBucket: 'care-31db0.appspot.com',
    iosBundleId: 'com.health.careapp.careApp.RunnerTests',
  );
}
